# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        project:
          - { name: "Fabric 1.21.5", path: "fabric_1.21.5", java: "21", distribution: "microsoft" }
          - { name: "Forge 1.8.9", path: "forge_1.8.9", java: "8", distribution: "temurin" }

    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup jdk ${{ matrix.project.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.project.java }}
          distribution: ${{ matrix.project.distribution }}

      - name: make gradle wrapper executable
        working-directory: ${{ matrix.project.path }}
        run: chmod +x ./gradlew

      - name: build
        working-directory: ${{ matrix.project.path }}
        run: ./gradlew build

      - name: capture build artifacts (${{ matrix.project.name }})
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts (${{ matrix.project.name }})
          path: ${{ matrix.project.path }}/build/libs/
